import { ROLE_KEYS, type RoleKey } from './roles';

export interface PermissionDefinition {
  key: string;
  resource: string;
  action: string;
  module: string;
  description: string;
  isDangerous?: boolean;
}

function def(
  key: string,
  module: string,
  description: string,
  isDangerous = false,
): PermissionDefinition {
  const [resource = '', action = ''] = key.split(':');
  return { key, resource, action, module, description, isDangerous };
}

export const PERMISSION_DEFINITIONS: PermissionDefinition[] = [
  // College
  def('college:read', 'College', 'View college profile'),
  def('college:update', 'College', 'Update college profile'),
  def('college:approve', 'College', 'Approve or reject a college registration', true),
  def('college:suspend', 'College', 'Suspend a college', true),
  def('college:settings', 'College', 'Manage college settings'),

  // Department
  def('department:read', 'Department', 'View departments'),
  def('department:create', 'Department', 'Create departments'),
  def('department:update', 'Department', 'Update departments'),
  def('department:delete', 'Department', 'Delete departments'),

  // Batch
  def('batch:read', 'Batch', 'View batches'),
  def('batch:create', 'Batch', 'Create batches'),
  def('batch:update', 'Batch', 'Update batches'),
  def('batch:delete', 'Batch', 'Delete batches'),
  def('batch:assign_advisor', 'Batch', 'Assign a class advisor'),
  def('batch:promote', 'Batch', 'Advance a batch to the next semester', true),

  // Student
  def('student:read', 'Student', 'View students in scope'),
  def('student:read_all', 'Student', 'View every student in the college'),
  // Self-service, deliberately separate from `student:read` so granting a
  // student access to their own record does not open the student list.
  def('student:read_own', 'Student', 'View own student profile'),
  def('student:update_own', 'Student', 'Update own contact details'),
  def('student:create', 'Student', 'Create students'),
  def('student:update', 'Student', 'Update students'),
  def('student:delete', 'Student', 'Delete students'),
  def('student:import', 'Student', 'Bulk import students'),
  def('student:export', 'Student', 'Export student data'),
  def('student:approve', 'Student', 'Approve pending student registrations'),

  // Faculty
  def('faculty:read', 'Faculty', 'View faculty'),
  def('faculty:create', 'Faculty', 'Create faculty'),
  def('faculty:update', 'Faculty', 'Update faculty'),
  def('faculty:delete', 'Faculty', 'Delete faculty'),
  def('faculty:import', 'Faculty', 'Bulk import faculty'),

  // Course
  def('course:read', 'Course', 'View courses'),
  def('course:create', 'Course', 'Create courses'),
  def('course:update', 'Course', 'Update courses'),
  def('course:delete', 'Course', 'Delete courses'),
  def('course:publish', 'Course', 'Publish courses'),
  def('course:enroll_students', 'Course', 'Enrol students into courses'),

  // Material
  def('material:read', 'Course', 'View learning materials'),
  def('material:create', 'Course', 'Create learning materials'),
  def('material:update', 'Course', 'Update learning materials'),
  def('material:delete', 'Course', 'Delete learning materials'),

  // Live class
  def('liveclass:read', 'Live Class', 'View live classes'),
  def('liveclass:create', 'Live Class', 'Schedule live classes'),
  def('liveclass:update', 'Live Class', 'Update live classes'),
  def('liveclass:cancel', 'Live Class', 'Cancel live classes'),
  def('liveclass:join_host', 'Live Class', 'Join a live class as host'),

  // Assignment
  def('assignment:read', 'Assignment', 'View assignments'),
  def('assignment:create', 'Assignment', 'Create assignments'),
  def('assignment:update', 'Assignment', 'Update assignments'),
  def('assignment:delete', 'Assignment', 'Delete assignments'),
  def('assignment:grade', 'Assignment', 'Grade submissions'),
  def('assignment:submit', 'Assignment', 'Submit an assignment'),

  // Exam
  def('exam:read', 'Exam', 'View exams'),
  def('exam:create', 'Exam', 'Create exams'),
  def('exam:update', 'Exam', 'Update exams'),
  def('exam:delete', 'Exam', 'Delete exams'),
  def('exam:publish', 'Exam', 'Publish exams'),
  def('exam:attempt', 'Exam', 'Attempt an exam'),
  def('exam:grade', 'Exam', 'Manually grade exam answers'),
  def('exam:view_results_all', 'Exam', 'View all students exam results'),
  def('exam:invalidate_attempt', 'Exam', 'Invalidate an exam attempt', true),

  // Question
  def('question:read', 'Question', 'View the question bank'),
  def('question:create', 'Question', 'Create questions'),
  def('question:update', 'Question', 'Update questions'),
  def('question:delete', 'Question', 'Delete questions'),

  // Attendance
  def('attendance:read', 'Attendance', 'View attendance in scope'),
  def('attendance:read_all', 'Attendance', 'View all attendance in the college'),
  // Self-service only. Kept separate from `attendance:read` because that one
  // also unlocks batch reports and defaulter lists, which name other students.
  def('attendance:read_own', 'Attendance', 'View own attendance'),
  def('attendance:mark', 'Attendance', 'Mark attendance'),
  def('attendance:update', 'Attendance', 'Correct attendance records'),
  def('attendance:lock', 'Attendance', 'Lock an attendance session'),
  def('attendance:override_lock', 'Attendance', 'Edit a locked attendance session', true),
  def('attendance:export', 'Attendance', 'Export attendance'),

  // Grade scale
  def('gradescale:read', 'Examination', 'View grading scales'),
  // Editing a scale re-grades every future exam that uses it, so creation and
  // revision are one permission rather than several.
  def('gradescale:manage', 'Examination', 'Create and revise grading scales', true),

  // Marks
  def('marks:read', 'Examination', 'View entered marks'),
  def('marks:enter', 'Examination', 'Enter and submit marks'),
  def('marks:verify', 'Examination', 'Verify and lock submitted marks'),
  // Separate from `marks:enter`: correcting a locked or published mark is a
  // different act of authority from entering one for the first time.
  def('marks:correct', 'Examination', 'Correct locked or published marks', true),

  // Result
  def('result:read', 'Result', 'View results in scope'),
  def('result:read_all', 'Result', 'View all results'),
  // Self-service only. Kept separate from `result:read` because that one also
  // unlocks mark sheets and rank lists naming other students.
  def('result:read_own', 'Result', 'View own results'),
  def('result:create', 'Result', 'Create results'),
  def('result:update', 'Result', 'Update results'),
  def('result:publish', 'Result', 'Publish results', true),
  def('result:withhold', 'Result', 'Withhold results', true),
  def('result:recalculate', 'Result', 'Recalculate published results', true),

  // Transcript
  def('transcript:read', 'Examination', 'View student transcripts'),
  def('transcript:read_own', 'Examination', 'View own transcript'),
  def('transcript:generate', 'Examination', 'Generate or regenerate transcripts'),

  // Certificate
  def('certificate:read', 'Certificate', 'View certificates'),
  def('certificate:issue', 'Certificate', 'Issue certificates'),
  def('certificate:revoke', 'Certificate', 'Revoke certificates', true),
  def('certificate:bulk_issue', 'Certificate', 'Bulk issue certificates'),

  // Company
  def('company:read', 'Company', 'View companies'),
  def('company:create', 'Company', 'Create companies'),
  def('company:update', 'Company', 'Update companies'),
  def('company:blacklist', 'Company', 'Blacklist a company', true),
  def('company:verify', 'Company', 'Verify a company'),

  // Job
  def('job:read', 'Job', 'View job postings'),
  def('job:create', 'Job', 'Create job postings'),
  def('job:update', 'Job', 'Update job postings'),
  def('job:delete', 'Job', 'Delete job postings'),
  def('job:publish', 'Job', 'Publish job postings'),
  def('job:close', 'Job', 'Close job postings'),

  // Application
  def('application:read', 'Application', 'View own applications'),
  def('application:read_all', 'Application', 'View all applications'),
  def('application:create', 'Application', 'Apply to a job'),
  def('application:withdraw', 'Application', 'Withdraw an application'),
  def('application:shortlist', 'Application', 'Shortlist applicants'),
  def('application:reject', 'Application', 'Reject applicants'),

  // Interview
  def('interview:read', 'Interview', 'View own interviews'),
  def('interview:read_all', 'Interview', 'View all interviews'),
  def('interview:schedule', 'Interview', 'Schedule interviews'),
  def('interview:update', 'Interview', 'Update interviews'),
  def('interview:record_result', 'Interview', 'Record interview results'),
  // Answering an interview — confirming a slot, asking for another time. Held
  // by students alone, mirroring `placement:respond`: reading an interview must
  // never imply the right to change one.
  def('interview:respond', 'Interview', 'Respond to own interviews'),

  // Placement
  def('placement:read', 'Placement', 'View own placement records'),
  def('placement:read_all', 'Placement', 'View all placement records'),
  def('placement:create', 'Placement', 'Record a placement'),
  def('placement:update', 'Placement', 'Update a placement'),
  // Accepting or declining an offer is the student's own decision, so it is
  // separate from `placement:update` — the office may correct a record's
  // details without being able to answer on the student's behalf.
  def('placement:respond', 'Placement', 'Accept or decline an offer'),
  def('placement:verify', 'Placement', 'Verify a placement'),
  def('placement:report', 'Placement', 'Generate placement reports'),

  // Training
  def('training:read', 'Training', 'View training requests'),
  def('training:create', 'Training', 'Create training requests'),
  def('training:update', 'Training', 'Update training requests'),
  def('training:approve', 'Training', 'Approve training requests'),
  def('training:reject', 'Training', 'Reject training requests'),
  def('training:assign_trainer', 'Training', 'Assign trainers to a request'),

  // Notification
  def('notification:read', 'Notification', 'View notifications'),
  def('notification:send', 'Notification', 'Send notifications'),
  def('announcement:create', 'Notification', 'Create announcements'),
  def('announcement:publish', 'Notification', 'Publish announcements'),

  // Support
  def('ticket:read', 'Support', 'View own tickets'),
  def('ticket:read_all', 'Support', 'View all tickets'),
  def('ticket:create', 'Support', 'Raise tickets'),
  def('ticket:update', 'Support', 'Update tickets'),
  def('ticket:assign', 'Support', 'Assign tickets'),
  def('ticket:resolve', 'Support', 'Resolve tickets'),
  def('ticket:internal_note', 'Support', 'Add internal notes'),

  // Audit
  def('audit:read', 'Audit', 'View audit logs'),
  def('audit:export', 'Audit', 'Export audit logs'),

  // Analytics
  def('analytics:read', 'Analytics', 'View analytics in scope'),
  def('analytics:read_all', 'Analytics', 'View all analytics'),
  def('report:generate', 'Analytics', 'Generate reports'),
  def('report:export', 'Analytics', 'Export reports'),

  // User
  def('user:read', 'User', 'View users'),
  def('user:create', 'User', 'Create users'),
  def('user:update', 'User', 'Update users'),
  def('user:suspend', 'User', 'Suspend users', true),
  def('user:reset_password', 'User', 'Reset a user password', true),
  def('user:impersonate', 'User', 'Impersonate another user', true),

  // Role
  def('role:read', 'Role', 'View roles'),
  def('role:create', 'Role', 'Create custom roles'),
  def('role:update', 'Role', 'Update roles'),
  def('role:delete', 'Role', 'Delete roles'),
  def('role:assign', 'Role', 'Assign roles to users', true),

  // Settings
  def('settings:read', 'Settings', 'View settings'),
  def('settings:update', 'Settings', 'Update settings'),

  // File
  def('file:upload', 'File', 'Upload files'),
  def('file:delete', 'File', 'Delete files'),
];

export const PERMISSIONS = PERMISSION_DEFINITIONS.map((p) => p.key);

export const PERMISSION_SET = new Set(PERMISSIONS);

export const WILDCARD_PERMISSION = '*:*';

/**
 * Default permission grants per role. `platform_admin` holds the global wildcard.
 * Row-level narrowing (own department / own batches / self) is applied by the
 * server-side scope guard, not expressible here.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, string[]> = {
  [ROLE_KEYS.PLATFORM_ADMIN]: [WILDCARD_PERMISSION],

  [ROLE_KEYS.COLLEGE_ADMIN]: [
    'college:read',
    'college:update',
    'college:settings',
    'department:read',
    'department:create',
    'department:update',
    'department:delete',
    'batch:read',
    'batch:create',
    'batch:update',
    'batch:delete',
    'batch:assign_advisor',
    'batch:promote',
    'student:read',
    'student:read_all',
    'student:create',
    'student:update',
    'student:delete',
    'student:import',
    'student:export',
    'student:approve',
    'faculty:read',
    'faculty:create',
    'faculty:update',
    'faculty:delete',
    'faculty:import',
    'course:read',
    'course:create',
    'course:update',
    'course:delete',
    'course:publish',
    'course:enroll_students',
    'material:read',
    'material:create',
    'material:update',
    'material:delete',
    'liveclass:read',
    'liveclass:create',
    'liveclass:update',
    'liveclass:cancel',
    'assignment:read',
    'assignment:create',
    'assignment:update',
    'assignment:delete',
    'assignment:grade',
    'exam:read',
    'exam:create',
    'exam:update',
    'exam:delete',
    'exam:publish',
    'exam:grade',
    'exam:view_results_all',
    'exam:invalidate_attempt',
    'question:read',
    'question:create',
    'question:update',
    'question:delete',
    'attendance:read',
    'attendance:read_all',
    'attendance:mark',
    'attendance:update',
    'attendance:lock',
    'attendance:override_lock',
    'attendance:export',
    'gradescale:read',
    'gradescale:manage',
    'marks:read',
    'marks:enter',
    'marks:verify',
    'marks:correct',
    'result:read',
    'result:read_all',
    'result:create',
    'result:update',
    'result:publish',
    'result:withhold',
    'result:recalculate',
    'transcript:read',
    'transcript:generate',
    'certificate:read',
    'certificate:issue',
    'certificate:revoke',
    'certificate:bulk_issue',
    // The college admin is the tenant's superuser and runs placement when
    // there is no dedicated officer, so it holds the full company and job set.
    'company:read',
    'company:create',
    'company:update',
    'company:verify',
    'company:blacklist',
    'job:read',
    'job:create',
    'job:update',
    'job:delete',
    'job:publish',
    'job:close',
    'application:read',
    'application:read_all',
    'application:shortlist',
    'application:reject',
    'interview:read_all',
    'interview:schedule',
    'interview:update',
    'interview:record_result',
    'placement:read_all',
    'placement:create',
    'placement:update',
    'placement:verify',
    'placement:report',
    'training:read',
    'training:create',
    'training:update',
    // A college admin is the final approver and schedules the delivery.
    'training:approve',
    'training:reject',
    'training:assign_trainer',
    'notification:read',
    'notification:send',
    'announcement:create',
    'announcement:publish',
    'ticket:read',
    'ticket:read_all',
    'ticket:create',
    'ticket:update',
    'ticket:assign',
    'ticket:resolve',
    'ticket:internal_note',
    'audit:read',
    'audit:export',
    'analytics:read',
    'analytics:read_all',
    'report:generate',
    'report:export',
    'user:read',
    'user:create',
    'user:update',
    'user:suspend',
    'user:reset_password',
    'role:read',
    'role:create',
    'role:update',
    'role:delete',
    'role:assign',
    'settings:read',
    'settings:update',
    'file:upload',
    'file:delete',
  ],

  [ROLE_KEYS.HOD]: [
    'college:read',
    'department:read',
    'batch:read',
    'batch:create',
    'batch:update',
    'batch:assign_advisor',
    'student:read',
    'student:create',
    'student:update',
    'student:import',
    'student:export',
    'student:approve',
    'faculty:read',
    'faculty:create',
    'faculty:update',
    'course:read',
    'course:create',
    'course:update',
    'course:publish',
    'material:read',
    'material:create',
    'material:update',
    'liveclass:read',
    'liveclass:create',
    'liveclass:update',
    'liveclass:cancel',
    'assignment:read',
    'assignment:create',
    'assignment:update',
    'assignment:grade',
    'exam:read',
    'exam:create',
    'exam:update',
    'exam:publish',
    'exam:grade',
    'exam:view_results_all',
    'question:read',
    'question:create',
    'question:update',
    'attendance:read',
    'attendance:mark',
    'attendance:update',
    'attendance:lock',
    'attendance:export',
    'gradescale:read',
    'marks:read',
    'marks:enter',
    // An HOD signs off marks for their department before results are published.
    'marks:verify',
    'marks:correct',
    'result:read',
    'result:create',
    'result:update',
    'transcript:read',
    'transcript:generate',
    'certificate:read',
    'certificate:issue',
    'application:read_all',
    'interview:read_all',
    'placement:read_all',
    'training:read',
    'training:create',
    'training:update',
    'training:approve',
    'training:reject',
    // An HOD schedules delivery within their own department.
    'training:assign_trainer',
    'notification:read',
    'notification:send',
    'announcement:create',
    'announcement:publish',
    'ticket:read',
    'ticket:create',
    'analytics:read',
    'report:generate',
    'report:export',
    'file:upload',
  ],

  [ROLE_KEYS.FACULTY]: [
    'college:read',
    'department:read',
    'batch:read',
    'student:read',
    'faculty:read',
    'course:read',
    'course:create',
    'course:update',
    'material:read',
    'material:create',
    'material:update',
    'liveclass:read',
    'liveclass:create',
    'liveclass:update',
    'liveclass:cancel',
    'liveclass:join_host',
    'assignment:read',
    'assignment:create',
    'assignment:update',
    'assignment:delete',
    'assignment:grade',
    'exam:read',
    'exam:create',
    'exam:update',
    'exam:publish',
    'exam:grade',
    'exam:view_results_all',
    'question:read',
    'question:create',
    'question:update',
    'attendance:read',
    'attendance:mark',
    'attendance:update',
    'attendance:lock',
    'attendance:export',
    'gradescale:read',
    'marks:read',
    // Faculty enter marks for their own subjects; verification sits above them.
    'marks:enter',
    'result:read',
    'result:create',
    'result:update',
    'certificate:read',
    'notification:read',
    'announcement:create',
    'ticket:read',
    'ticket:create',
    'analytics:read',
    'report:generate',
    'file:upload',
  ],

  [ROLE_KEYS.TRAINER]: [
    'college:read',
    'department:read',
    'batch:read',
    'student:read',
    'course:read',
    'course:create',
    'course:update',
    'material:read',
    'material:create',
    'material:update',
    'liveclass:read',
    'liveclass:create',
    'liveclass:update',
    'liveclass:cancel',
    'liveclass:join_host',
    'assignment:read',
    'assignment:create',
    'assignment:update',
    'assignment:grade',
    'exam:read',
    'exam:create',
    'exam:update',
    'exam:publish',
    'exam:grade',
    'exam:view_results_all',
    'question:read',
    'question:create',
    'attendance:read',
    'attendance:mark',
    'attendance:update',
    'attendance:export',
    'marks:read',
    // A trainer grades the assessment attached to their own training session.
    'marks:enter',
    'result:read',
    'training:read',
    'notification:read',
    'announcement:create',
    'ticket:read',
    'ticket:create',
    'analytics:read',
    'file:upload',
  ],

  [ROLE_KEYS.PLACEMENT_OFFICER]: [
    'college:read',
    'department:read',
    'batch:read',
    'student:read',
    'student:read_all',
    'student:export',
    'company:read',
    'company:create',
    'company:update',
    'company:blacklist',
    'job:read',
    'job:create',
    'job:update',
    'job:delete',
    'job:publish',
    'job:close',
    'application:read_all',
    'application:shortlist',
    'application:reject',
    'interview:read_all',
    'interview:schedule',
    'interview:update',
    'interview:record_result',
    'placement:read_all',
    'placement:create',
    'placement:update',
    'placement:verify',
    'placement:report',
    'attendance:read_all',
    'result:read_all',
    // Eligibility for most drives is stated as a CGPA and backlog count.
    'transcript:read',
    'notification:read',
    'notification:send',
    'announcement:create',
    'announcement:publish',
    'ticket:read',
    'ticket:create',
    'analytics:read',
    'report:generate',
    'report:export',
    'file:upload',
  ],

  [ROLE_KEYS.STUDENT]: [
    'college:read',
    'student:read_own',
    'student:update_own',
    'course:read',
    'material:read',
    'liveclass:read',
    'assignment:read',
    'assignment:submit',
    'exam:read',
    'exam:attempt',
    'attendance:read_own',
    // `result:read` would also unlock mark sheets naming classmates.
    'result:read_own',
    'transcript:read_own',
    'certificate:read',
    'company:read',
    'job:read',
    'application:read',
    'application:create',
    'application:withdraw',
    'interview:read',
    'interview:respond',
    'placement:read',
    'placement:respond',
    'notification:read',
    'ticket:read',
    'ticket:create',
    'analytics:read',
    'file:upload',
  ],
};
